### ISSUE TITLE
No vegetation for vanilla and modded biomes on the island if the another island is placed below the island

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [klinbee/Aetherial-Islands#3]
Related to #2 in `Overall Feedback: Biomes`

## Modpack Environment

Tested mods: (I had randomly picked and scrambled around to find out inconsistencies)
Minecraft: **1.21.1**
NeoForge: **21.1.72**
Sinytra Connector: **2.0.0-beta.3**
Connector Extras: **1.12.1+1.21.1**
Forgified Fabric API: **0.104.0+2.0.15+1.21.1**
Aetherial Islands: **1.0.3+mod**
[Fabric] Nature's Spirit: **1.6.3**
Biomes O' Plenty: **21.1.0.7-neoforge**
ChoiceTheorem's Ovehauled Villages: **3.5.3a**
Moog's Soaring Structures: **1.2.5**
Oh The Biomes We've Gone: **2.1.5**
Regions Unexplored: **0.5.6.1**
Structory: **1.3.6**
Sky Villages: **1.0.6-1.21.x** 
Lithostitched: **1.21-1.3.1a**

## Description
When playing with Aetherial Islands, you may notice some weird empty islands if they're placed below the island. Seems that datapack does not respect the vegetation for all layers, so the higher islands get trees, grass, structures, while the island that is spawned on lower Y values is missing everything except the grass blocks.

## Expected Behaviour

You get your trees, grass and some other vegetation spawning as expected on these islands.
![2024-11-02_06 27 03](https://github.com/user-attachments/assets/7f0039e6-8fc0-479b-b5cb-cdd0a05008fb)
*Screenshot is taken when I tried to fix this myself, somewhat like this should happen. But my solution is somewhat crashy and not works with vanilla biomes.

## Real Behaviour
You get empty islands with grass and stone, where the islands are generating below the another island.

Examples:
![2024-11-02_06 26 07](https://github.com/user-attachments/assets/bd44c334-a7f1-42ac-8ee3-494a59d5e486)
![2024-11-02_06 26 11](https://github.com/user-attachments/assets/46e39d81-147e-46d6-aa2e-ff210c3797a4)
![2024-11-08_03 38 44](https://github.com/user-attachments/assets/7d878e0a-8e35-4e61-b3a2-9b3992e3fd6d)
![2024-11-08_03 42 27](https://github.com/user-attachments/assets/23668a53-c1eb-45bf-a623-aeb5326efc9b)
(↑ You can see the island above here, there are mostly no grass on the island below)
![2024-11-08_03 42 31](https://github.com/user-attachments/assets/c9969df3-4da4-4c67-a8ed-b883da178b80)
![2024-11-08_03 42 40](https://github.com/user-attachments/assets/f6d5e5c0-2892-4b26-8a9b-f13c0e29e067)
![2024-11-08_03 42 44](https://github.com/user-attachments/assets/622c614a-eeda-4bea-865f-0e6fe3df8899)
(↑ two screenshots of the same islands with different camera perspectives)
![2024-11-08_03 43 28](https://github.com/user-attachments/assets/acb93d44-c8c4-44cf-912f-43c41f325ecc)
![2024-11-08_10 06 56](https://github.com/user-attachments/assets/d581d275-f8cb-47a4-8475-1ef792f2b418)
![2024-11-08_10 27 32](https://github.com/user-attachments/assets/818e5851-e669-4b94-abcf-72f076b1bfbf)
(↑ **Biomes O' Plenty** is very sensitive to this bug and you can reporduce the bug much easier with this mod installed)
![2024-11-08_10 28 16](https://github.com/user-attachments/assets/84813f10-d440-4bb4-aff5-c8aa1b98ca6a)
(↑ The same screenshot with Night Vision effect)

Also to note, that there are also some weird occasions that the island turn to a flat cave biome related island due to the Y level, such as:
![2024-11-08_10 01 17](https://github.com/user-attachments/assets/624778a9-3aa3-4409-8d34-9445038e978e)
(the island could ignore that and have more smooth transition? I'm not sure that is possible due to worldgen limitations however)

The bug also happen with the cave biomes. Here you can see the issue properly. The same island have TWO separated biomes. The islands above are cave related ones, the one below is just a... Mushroom Island biome? But with the Sculk biome replaced the Mushroom Island biome. The another island below is just an ocean.
![2024-11-08_10 03 43](https://github.com/user-attachments/assets/4863375e-b325-4665-b425-d0fdf41fee67)

## Conclusion and Solution
The bug is quite annoying and these random empty parts of the islands are pretty common, so I decided to report this here, because I believe that player could be able to have their vegetation spawned as expected. As a solution, you can try to populate the vegetation to all Y levels. The grass and tress may spawn in the cave biomes, but practically it may be more fun and rewarding solution, rather than just empty parts of the islands.

**Comment by klinbee** [comment]
This is just how the mod developer coded their feature's placement to be on the world surface. Obviously the world surface will only be the top most island. I changed all the vanilla ones programmatically to account for this. It is not something that can be done trivially to every feature for every mod and would need to be done individually on a mod by mod basis, on a feature by feature basis. This will not be fixed. Compatibility packs may be made if someone commissions it though.
