### ISSUE TITLE
The islands is turning into "spaghetti" wherever the biome have their own configured/placed feature splitted into two biomes.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [klinbee/Aetherial-Islands#4]
## Modpack Environment

Tested mods: (I had randomly picked and scrambled around to find out inconsistencies)
Minecraft: **1.21.1**
NeoForge: **21.1.72**
Sinytra Connector: **2.0.0-beta.3**
Connector Extras: **1.12.1+1.21.1**
Forgified Fabric API: **0.104.0+2.0.15+1.21.1**
Aetherial Islands: **1.0.3+mod**
[Fabric] Nature's Spirit: **1.6.3**
Biomes O' Plenty: **21.1.0.7-neoforge**
ChoiceTheorem's Ovehauled Villages: **3.5.3a**
Moog's Soaring Structures: **1.2.5**
Oh The Biomes We've Gone: **2.1.5**
Regions Unexplored: **0.5.6.1**
Structory: **1.3.6**
Sky Villages: **1.0.6-1.21.x** 
Lithostitched: **1.21-1.3.1a**

## Description
I have noticed that when I was testing the mods around and found quite rare, but very funny islands behaviour, when the structure can "join" two or more islands with their respective jigsaw feature placement providers.

## Expected Behaviour
Islands not connecting to each other and not turning into a "spaghetti"-like islands, so the player need to use water or flight options to move around.

## Real Behaviour
You get "spaghetti", lol. The player can simply go dig the island and move on.

Examples:
![2024-11-08_09 59 26](https://github.com/user-attachments/assets/d281ffa3-e2f7-43c4-be09-37c25a323582)
![2024-11-08_10 08 26](https://github.com/user-attachments/assets/707afdd6-2fed-4b6d-8dab-7069e79ac4f8)
![2024-11-08_10 14 40](https://github.com/user-attachments/assets/5c4cdad9-bdfe-4994-bc1f-810b91e6b0ae)
(↑ not the spaghetti ones, but the biome have some providers making the island looking somewhat blocky)

## Conclusion and Solution
I'm still really unsure if this needs to be even reported, but I got some fun when I found that. Probably if you fine with that, you can turn this to a feature and close the issue. If not, probably a feature placement should be checked for multiple biomes and island boundaries to not do such things. lol

**Comment by klinbee** [comment]
This is just how the mod developer coded their structure, I have no control over this at all.
